version: "3.9"

services:
  redis:
    image: redis:6
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - redisdata:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: teste-123

volumes:
  postgresdata:
  redisdata:
